import AppKit
import CoreGraphics
import ImageIO
import QuickLookUI
import UniformTypeIdentifiers

/// File I/O is kept off the main actor so a large stack cannot block the menu.
enum NativeScreenshotThumbnailFileStore {
    static func save(
        pngData: Data,
        in directory: URL,
        basename: String,
        format: NativeScreenshotImageProcessor.FileFormat,
        quality: CGFloat
    ) throws -> URL {
        try FileManager.default.createDirectory(at: directory,
                                                withIntermediateDirectories: true)
        let encoded: Data
        if format == .png {
            encoded = pngData
        } else {
            guard let source = CGImageSourceCreateWithData(pngData as CFData, nil),
                  let image = CGImageSourceCreateImageAtIndex(source, 0, nil) else {
                throw NativeScreenshotImageProcessor.ImageError.invalidImage
            }
            encoded = try NativeScreenshotImageProcessor.encode(
                image, as: format, quality: quality)
        }
        // The random suffix prevents two rapid saves from selecting the same
        // pathname, including when separate cards are saved concurrently.
        let name = "\(basename)-\(UUID().uuidString.prefix(8))"
        let url = directory.appendingPathComponent(name)
            .appendingPathExtension(format.rawValue)
        try encoded.write(to: url, options: .atomic)
        return url
    }

    static func saveAll(
        pngData: [Data],
        in directory: URL,
        basename: String,
        format: NativeScreenshotImageProcessor.FileFormat,
        quality: CGFloat
    ) throws -> [URL] {
        var saved: [URL] = []
        do {
            for (index, data) in pngData.enumerated() {
                try Task<Never, Never>.checkCancellation()
                let name = "\(basename)-\(String(format: "%02d", index + 1))"
                saved.append(try save(pngData: data, in: directory, basename: name,
                                      format: format, quality: quality))
            }
        } catch {
            // A failed batch must not leave a silent partial save. Every path
            // here was generated by this invocation, so rollback is scoped.
            for url in saved { try? FileManager.default.removeItem(at: url) }
            throw error
        }
        return saved
    }
}

/// The hover controls keep the two frequent actions in the center and reserve
/// the corners for dismissal, pinning, editing, and sharing.
struct NativeScreenshotThumbnailHoverLayout {
    let close: CGRect
    let pin: CGRect
    let edit: CGRect
    let share: CGRect
    let copy: CGRect
    let save: CGRect

    static func make(in size: CGSize) -> Self {
        let scale = min(2, max(0.55, min(size.width / 240, size.height / 160)))
        let padding = max(5, (10 * scale).rounded())
        let corner = max(18, (28 * scale).rounded())
        let centerHeight = max(18, (32 * scale).rounded())
        let gap = max(4, (8 * scale).rounded())
        let centerWidth = min(size.width - padding * 2,
                              max(64, (110 * scale).rounded()))
        let centerX = (size.width - centerWidth) / 2
        let saveY = (size.height - centerHeight * 2 - gap) / 2
        return Self(
            close: CGRect(x: padding, y: size.height - padding - corner,
                          width: corner, height: corner),
            pin: CGRect(x: size.width - padding - corner,
                        y: size.height - padding - corner,
                        width: corner, height: corner),
            edit: CGRect(x: padding, y: padding, width: corner, height: corner),
            share: CGRect(x: size.width - padding - corner, y: padding,
                          width: corner, height: corner),
            copy: CGRect(x: centerX, y: saveY + centerHeight + gap,
                         width: centerWidth, height: centerHeight),
            save: CGRect(x: centerX, y: saveY,
                         width: centerWidth, height: centerHeight)
        )
    }
}

#if !NATIVE_SCREENSHOT_THUMBNAIL_FILE_TEST
/// Short-lived preview of a completed capture. The presenter retains only
/// reduced images and at most four cards, even during rapid consecutive shots.
@MainActor
final class NativeScreenshotThumbnailPresenter {
    struct Actions {
        var copy: (Data) -> Void
        var save: (Data) -> Void
        var saveAs: (Data) -> Void
        var pin: (Data) -> Void
        var edit: (Data) -> Void
    }

    static let shared = NativeScreenshotThumbnailPresenter()
    private var cards: [Card] = []
    private let maximumCards = 4
    private let maximumRetainedBytes = 128 * 1024 * 1024
    private var isSavingAll = false
    private init() {}

    func present(
        image: CGImage,
        actions: Actions,
        force: Bool = false,
        estimatedBytes: Int = 0,
        pngData: Data? = nil
    ) {
        guard (force || PreferencesManager.shared.showFloatingThumbnail),
              let preview = makePreview(image) else { return }
        let card = Card(preview: preview, actions: actions, pngData: pngData,
                        retainedBytes: estimatedBytes) { [weak self] card in
            self?.remove(card)
        }
        if !PreferencesManager.shared.thumbnailStacking {
            for card in cards { card.close() }
            cards.removeAll()
        }
        cards.append(card)
        trimCards()
        reposition()
        card.show()
    }

    private func trimCards() {
        while cards.count > maximumCards
            || (cards.count > 1
                && cards.reduce(0, { $0 + $1.retainedBytes }) > maximumRetainedBytes) {
            cards.removeFirst().close()
        }
    }

    func dismissAll() {
        for card in cards { card.close() }
        cards.removeAll()
    }

    private func saveAll() {
        guard !isSavingAll else { return }
        let pending = cards
        let data = pending.compactMap(\.pngData)
        guard !data.isEmpty else { return }
        isSavingAll = true
        pending.forEach { $0.pauseExpiry() }
        let panel = NSOpenPanel()
        panel.canChooseFiles = false
        panel.canChooseDirectories = true
        panel.canCreateDirectories = true
        panel.allowsMultipleSelection = false
        panel.level = .modalPanel
        panel.prompt = NativeScreenshotUserText.string("保存到此文件夹", "Save to This Folder")
        panel.message = NativeScreenshotUserText.string(
            "为所有截图选择一个保存文件夹", "Choose one folder for all screenshots")
        NSApp.activate(ignoringOtherApps: true)
        panel.begin { [weak self] response in
            guard let self else { return }
            guard response == .OK, let directory = panel.url else {
                self.isSavingAll = false
                pending.forEach { $0.resumeExpiry() }
                return
            }
            let preferences = PreferencesManager.shared
            let format = NativeScreenshotImageProcessor.FileFormat(
                rawValue: preferences.imageFormat) ?? .png
            let quality = CGFloat(preferences.imageQuality)
            let basename = ScreenshotSaveService.defaultFilename()
            Task { @MainActor [weak self] in
                do {
                    _ = try await Task.detached(priority: .userInitiated) {
                        try NativeScreenshotThumbnailFileStore.saveAll(
                            pngData: data, in: directory, basename: basename,
                            format: format, quality: quality)
                    }.value
                    pending.forEach { $0.dismiss() }
                } catch {
                    pending.forEach { $0.resumeExpiry() }
                    NSAlert(error: error).runModal()
                }
                self?.isSavingAll = false
            }
        }
    }

    private func remove(_ card: Card) {
        cards.removeAll { $0 === card }
        card.close()
        reposition()
    }

    private func reposition() {
        guard let screen = NSScreen.main ?? NSScreen.screens.first else { return }
        let visible = screen.visibleFrame
        let corner = PreferencesManager.shared.thumbnailCorner
        let left = corner == "bottomLeft" || corner == "topLeft"
        let top = corner == "topLeft" || corner == "topRight"
        var offset: CGFloat = 18
        for card in cards.reversed() {
            let size = card.window.frame.size
            let x = left ? visible.minX + 18 : visible.maxX - size.width - 18
            let y = top ? visible.maxY - size.height - offset : visible.minY + offset
            card.window.setFrameOrigin(NSPoint(x: x, y: y))
            offset += size.height + 10
        }
    }

    private func makePreview(_ image: CGImage) -> NSImage? {
        let scale = min(2, max(0.5, PreferencesManager.shared.thumbnailScale))
        let targetWidth = max(1, Int(240 * scale))
        let targetHeight = max(1, Int(160 * scale))
        let ratio = min(CGFloat(targetWidth) / CGFloat(image.width),
                        CGFloat(targetHeight) / CGFloat(image.height), 1)
        let width = max(1, Int((CGFloat(image.width) * ratio).rounded()))
        let height = max(1, Int((CGFloat(image.height) * ratio).rounded()))
        guard let colorSpace = CGColorSpace(name: CGColorSpace.sRGB),
              let canvas = CGContext(
                data: nil, width: width, height: height,
                bitsPerComponent: 8, bytesPerRow: 0, space: colorSpace,
                bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue
              ) else { return nil }
        canvas.interpolationQuality = .high
        canvas.draw(image, in: CGRect(x: 0, y: 0, width: width, height: height))
        guard let small = canvas.makeImage() else { return nil }
        return NSImage(cgImage: small, size: NSSize(width: width, height: height))
    }

    /// The image remains compressed until a drag destination asks for a file.
    /// Finder writes to its chosen destination on this bounded worker queue.
    private final class PNGFilePromise: NSObject, NSFilePromiseProviderDelegate,
                                         @unchecked Sendable {
        private static let pendingLock = NSLock()
        private static var pending: [UUID: PNGFilePromise] = [:]
        private let id = UUID()
        let data: Data
        let name: String
        private let queue: OperationQueue

        init(data: Data) {
            self.data = data
            name = "ClipyClone-\(UUID().uuidString.prefix(8)).png"
            queue = OperationQueue()
            queue.name = "ClipyClone thumbnail file promise"
            queue.maxConcurrentOperationCount = 1
            super.init()
        }

        func retainUntilDelivered() {
            Self.pendingLock.lock()
            Self.pending[id] = self
            Self.pendingLock.unlock()
            // A cancelled drag may never request a file. Bound that lifetime.
            DispatchQueue.main.asyncAfter(deadline: .now() + 120) { [weak self] in
                self?.releaseAfterDelivery()
            }
        }

        func releaseAfterDelivery() {
            Self.pendingLock.lock()
            Self.pending.removeValue(forKey: id)
            Self.pendingLock.unlock()
        }

        func filePromiseProvider(_ filePromiseProvider: NSFilePromiseProvider,
                                 fileNameForType fileType: String) -> String { name }

        func filePromiseProvider(_ filePromiseProvider: NSFilePromiseProvider,
                                 writePromiseTo url: URL,
                                 completionHandler: @escaping (Error?) -> Void) {
            let data = data
            queue.addOperation { [self] in
                defer { releaseAfterDelivery() }
                do {
                    try data.write(to: url, options: .atomic)
                    completionHandler(nil)
                } catch {
                    completionHandler(error)
                }
            }
        }
    }

    @MainActor
    private final class QuickLookPresenter: NSObject,
        QLPreviewPanelDataSource, QLPreviewPanelDelegate {
        static let shared = QuickLookPresenter()
        private var currentURL: URL?
        private var generation = 0

        func open(pngData: Data) {
            generation &+= 1
            let request = generation
            let url = FileManager.default.temporaryDirectory
                .appendingPathComponent("ClipyClone-QuickLook-\(UUID().uuidString).png")
            Task { @MainActor [weak self] in
                do {
                    try await Task.detached(priority: .userInitiated) {
                        try pngData.write(to: url, options: .atomic)
                    }.value
                    guard let self, self.generation == request else {
                        try? FileManager.default.removeItem(at: url)
                        return
                    }
                    guard let panel = QLPreviewPanel.shared() else {
                        try? FileManager.default.removeItem(at: url)
                        return
                    }
                    let oldURL = self.currentURL
                    self.currentURL = url
                    panel.dataSource = self
                    panel.delegate = self
                    panel.reloadData()
                    NSApp.activate(ignoringOtherApps: true)
                    panel.makeKeyAndOrderFront(nil)
                    if let oldURL {
                        // Quick Look can still be reading the prior item during
                        // its transition; release it after that handoff.
                        DispatchQueue.global(qos: .utility).asyncAfter(deadline: .now() + 60) {
                            try? FileManager.default.removeItem(at: oldURL)
                        }
                    }
                } catch {
                    try? FileManager.default.removeItem(at: url)
                    NSAlert(error: error).runModal()
                }
            }
        }

        func numberOfPreviewItems(in panel: QLPreviewPanel!) -> Int {
            currentURL == nil ? 0 : 1
        }

        func previewPanel(_ panel: QLPreviewPanel!, previewItemAt index: Int) -> QLPreviewItem! {
            guard index == 0, let currentURL else { return nil }
            return currentURL as NSURL
        }

        func windowWillClose(_ notification: Notification) {
            guard let panel = notification.object as? QLPreviewPanel,
                  panel.dataSource === self else { return }
            panel.dataSource = nil
            panel.delegate = nil
            if let currentURL { try? FileManager.default.removeItem(at: currentURL) }
            currentURL = nil
        }
    }

    private final class CardContentView: NSVisualEffectView {
        weak var owner: Card?
        private var mouseDownLocation: NSPoint?
        private var horizontalScroll: CGFloat = 0

        override func updateTrackingAreas() {
            super.updateTrackingAreas()
            for area in trackingAreas { removeTrackingArea(area) }
            addTrackingArea(NSTrackingArea(
                rect: .zero,
                options: [.mouseEnteredAndExited, .activeAlways, .inVisibleRect],
                owner: self, userInfo: nil
            ))
        }

        override func mouseEntered(with event: NSEvent) { owner?.setHovered(true) }
        override func mouseExited(with event: NSEvent) { owner?.setHovered(false) }

        override func mouseDown(with event: NSEvent) {
            mouseDownLocation = event.locationInWindow
            if event.clickCount >= 2 { owner?.perform(index: 3) }
        }

        override func mouseDragged(with event: NSEvent) {
            guard let start = mouseDownLocation else { return }
            let point = event.locationInWindow
            guard hypot(point.x - start.x, point.y - start.y) > 6 else { return }
            mouseDownLocation = nil
            owner?.beginFileDrag(with: event, from: self)
        }

        override func mouseUp(with event: NSEvent) { mouseDownLocation = nil }

        override func rightMouseDown(with event: NSEvent) {
            owner?.showContextMenu(with: event, in: self)
        }

        override func scrollWheel(with event: NSEvent) {
            if event.phase == .began { horizontalScroll = 0 }
            guard abs(event.scrollingDeltaX) > abs(event.scrollingDeltaY) else {
                horizontalScroll = 0
                return
            }
            horizontalScroll += event.scrollingDeltaX
            if abs(horizontalScroll) >= 45 {
                horizontalScroll = 0
                owner?.dismiss()
            }
        }
    }

    private final class PassiveImageView: NSView {
        var image: NSImage? { didSet { needsDisplay = true } }

        override func hitTest(_ point: NSPoint) -> NSView? { nil }

        override func draw(_ dirtyRect: NSRect) {
            guard let image, image.size.width > 0, image.size.height > 0,
                  bounds.width > 0, bounds.height > 0 else { return }
            NSBezierPath(roundedRect: bounds, xRadius: 12, yRadius: 12).addClip()
            let scale = max(bounds.width / image.size.width,
                            bounds.height / image.size.height)
            let drawSize = CGSize(width: image.size.width * scale,
                                  height: image.size.height * scale)
            image.draw(in: CGRect(x: (bounds.width - drawSize.width) / 2,
                                  y: (bounds.height - drawSize.height) / 2,
                                  width: drawSize.width, height: drawSize.height),
                       from: .zero, operation: .copy, fraction: 1)
        }
    }

    /// Uncovered pixels still belong to CardContentView so dragging the image
    /// to Finder and the existing edge-dismiss gesture remain available.
    private final class HoverOverlay: NSView {
        override func hitTest(_ point: NSPoint) -> NSView? {
            let local = convert(point, from: superview)
            for child in subviews.reversed() where child.frame.contains(local) {
                if let hit = child.hitTest(local) { return hit }
            }
            return nil
        }
    }

    @MainActor
    private final class Card: NSObject, NSDraggingSource {
        let window: NSPanel
        var retainedBytes: Int
        private let actions: Actions
        var pngData: Data?
        private var preview: NSImage
        private let onClose: (Card) -> Void
        private let hoverOverlay: HoverOverlay
        private let background: CardContentView
        private let imageView: PassiveImageView
        private var expiry: DispatchWorkItem?
        private var activePromise: PNGFilePromise?
        private var isPresentingApplicationPicker = false
        private var isProcessingImage = false
        private var dragStartScreenPoint: NSPoint?
        private var isClosed = false

        init(preview: NSImage, actions: Actions, pngData: Data?,
             retainedBytes: Int, onClose: @escaping (Card) -> Void) {
            self.actions = actions
            self.pngData = pngData
            self.preview = preview
            self.onClose = onClose
            self.retainedBytes = max(0, retainedBytes)
            let scale = CGFloat(min(2, max(0.5, PreferencesManager.shared.thumbnailScale)))
            let width = max(180, (240 * scale).rounded())
            let height = max(120, (160 * scale).rounded())
            window = NSPanel(
                contentRect: CGRect(x: 0, y: 0, width: width, height: height),
                styleMask: [.borderless, .nonactivatingPanel],
                backing: .buffered, defer: false
            )
            hoverOverlay = HoverOverlay(frame: CGRect(x: 0, y: 0, width: width, height: height))
            background = CardContentView(frame: CGRect(
                origin: .zero, size: NSSize(width: width, height: height)))
            imageView = PassiveImageView(frame: CGRect(
                x: 0, y: 0, width: width, height: height))
            super.init()
            window.level = .floating
            window.collectionBehavior = [.canJoinAllSpaces, .fullScreenAuxiliary]
            window.hasShadow = true
            window.isOpaque = false
            window.backgroundColor = .clear

            background.owner = self
            background.material = .hudWindow
            background.state = .active
            background.wantsLayer = true
            background.layer?.cornerRadius = 12
            background.layer?.masksToBounds = true
            background.layer?.borderWidth = 1
            background.layer?.borderColor = NSColor.white.withAlphaComponent(0.4).cgColor
            imageView.image = preview
            imageView.autoresizingMask = [.width, .height]
            imageView.setAccessibilityLabel(NativeScreenshotUserText.string(
                "截图缩略图，双击编辑，可拖入文件夹", "Screenshot thumbnail. Double-click to edit or drag to a folder"))
            background.addSubview(imageView)

            hoverOverlay.wantsLayer = true
            hoverOverlay.layer?.backgroundColor = NSColor.black.withAlphaComponent(0.45).cgColor
            hoverOverlay.layer?.cornerRadius = 12
            hoverOverlay.layer?.masksToBounds = true
            hoverOverlay.autoresizingMask = [.width, .height]
            hoverOverlay.isHidden = true
            installHoverButtons(size: CGSize(width: width, height: height))
            background.addSubview(hoverOverlay)
            window.contentView = background
        }

        private func installHoverButtons(size: CGSize) {
            let layout = NativeScreenshotThumbnailHoverLayout.make(in: size)
            let corners: [(CGRect, String, String, Int)] = [
                (layout.close, "xmark", NativeScreenshotUserText.string("关闭", "Close"), 4),
                (layout.pin, "pin.fill", NativeScreenshotUserText.string("贴图", "Pin"), 2),
                (layout.edit, "pencil", NativeScreenshotUserText.string("编辑", "Edit"), 3),
                (layout.share, "square.and.arrow.up", NativeScreenshotUserText.string("分享", "Share"), 5)
            ]
            for (frame, symbol, title, index) in corners {
                let button = NSButton(
                    image: NSImage(systemSymbolName: symbol,
                                   accessibilityDescription: title) ?? NSImage(),
                    target: self, action: #selector(performHoverAction(_:)))
                button.frame = frame
                button.tag = index
                button.isBordered = false
                button.contentTintColor = .white
                button.toolTip = title
                button.setAccessibilityLabel(title)
                button.setAccessibilityIdentifier("thumbnail.hover.\(index)")
                button.wantsLayer = true
                button.layer?.cornerRadius = frame.width / 2
                button.layer?.backgroundColor = NSColor.white.withAlphaComponent(0.18).cgColor
                button.layer?.borderWidth = 1
                button.layer?.borderColor = NSColor.white.withAlphaComponent(0.5).cgColor
                hoverOverlay.addSubview(button)
            }
            for (frame, title, index) in [
                (layout.copy, NativeScreenshotUserText.string("复制", "Copy"), 0),
                (layout.save, NativeScreenshotUserText.string("保存", "Save"), 1)
            ] {
                let button = NSButton(title: title, target: self,
                                      action: #selector(performHoverAction(_:)))
                button.frame = frame
                button.tag = index
                button.isBordered = false
                button.font = .systemFont(ofSize: max(9, 13 * frame.height / 32), weight: .medium)
                button.contentTintColor = NSColor(white: 0.1, alpha: 1)
                button.toolTip = title
                button.setAccessibilityLabel(title)
                button.setAccessibilityIdentifier("thumbnail.hover.\(index)")
                button.wantsLayer = true
                button.layer?.cornerRadius = frame.height / 2
                button.layer?.backgroundColor = NSColor.white.withAlphaComponent(0.88).cgColor
                hoverOverlay.addSubview(button)
            }
        }

        func show() {
            window.orderFrontRegardless()
            scheduleExpiry()
        }

        func close() {
            guard !isClosed else { return }
            isClosed = true
            cancelExpiry()
            window.orderOut(nil)
            window.contentView = nil
            activePromise = nil
            pngData = nil
        }

        func dismiss() { onClose(self) }

        func pauseExpiry() { cancelExpiry() }

        func resumeExpiry() {
            if !isClosed && !isPresentingApplicationPicker && !isProcessingImage
                && !NativeScreenshotThumbnailPresenter.shared.isSavingAll {
                scheduleExpiry()
            }
        }

        func setHovered(_ hovered: Bool) {
            guard !isClosed else { return }
            hoverOverlay.isHidden = !hovered
            if hovered { cancelExpiry() } else { resumeExpiry() }
        }

        func beginFileDrag(with event: NSEvent, from view: NSView) {
            guard !isClosed, let pngData else { return }
            cancelExpiry()
            let promise = PNGFilePromise(data: pngData)
            promise.retainUntilDelivered()
            activePromise = promise
            dragStartScreenPoint = window.convertPoint(toScreen: event.locationInWindow)
            let provider = NSFilePromiseProvider(fileType: UTType.png.identifier,
                                                 delegate: promise)
            let item = NSDraggingItem(pasteboardWriter: provider)
            item.setDraggingFrame(background.bounds, contents: preview)
            view.beginDraggingSession(with: [item], event: event, source: self)
        }

        func draggingSession(_ session: NSDraggingSession,
                             sourceOperationMaskFor context: NSDraggingContext) -> NSDragOperation {
            .copy
        }

        func draggingSession(_ session: NSDraggingSession, endedAt screenPoint: NSPoint,
                             operation: NSDragOperation) {
            if operation == [] { activePromise?.releaseAfterDelivery() }
            activePromise = nil
            let wasDraggedToEdge = dragStartScreenPoint.map {
                hypot(screenPoint.x - $0.x, screenPoint.y - $0.y) >= 60
                    && Self.isNearScreenEdge(screenPoint)
            } ?? false
            dragStartScreenPoint = nil
            if operation == .copy || wasDraggedToEdge { dismiss() }
            else { resumeExpiry() }
        }

        private static func isNearScreenEdge(_ point: NSPoint) -> Bool {
            guard let screen = NSScreen.screens.first(where: { $0.frame.contains(point) })
                ?? NSScreen.main else { return false }
            let frame = screen.frame
            let distance: CGFloat = 38
            return point.x <= frame.minX + distance
                || point.x >= frame.maxX - distance
                || point.y <= frame.minY + distance
                || point.y >= frame.maxY - distance
        }

        func showContextMenu(with event: NSEvent, in view: NSView) {
            cancelExpiry()
            let menu = NSMenu()
            addAction(NativeScreenshotUserText.string("复制", "Copy"), index: 0, to: menu)
            addAction(NativeScreenshotUserText.string("保存", "Save"), index: 1, to: menu)
            menu.addItem(withTitle: NativeScreenshotUserText.string("另存为…", "Save As..."),
                         action: #selector(saveAsFromMenu), keyEquivalent: "").target = self
            menu.addItem(.separator())
            addAction(NativeScreenshotUserText.string("在编辑器中打开", "Open in Editor"),
                      index: 3, to: menu)
            addAction(NativeScreenshotUserText.string("贴到屏幕", "Pin to Screen"),
                      index: 2, to: menu)
            menu.addItem(withTitle: NativeScreenshotUserText.string("快速预览", "Quick Look"),
                         action: #selector(previewImage), keyEquivalent: "").target = self
            menu.addItem(withTitle: NativeScreenshotUserText.string("识别文字与二维码", "Run OCR & QR"),
                         action: #selector(runRecognition), keyEquivalent: "").target = self
            menu.addItem(.separator())
            let transforms = NSMenu()
            for (index, title) in [
                NativeScreenshotUserText.string("向左旋转", "Rotate Left"),
                NativeScreenshotUserText.string("向右旋转", "Rotate Right"),
                NativeScreenshotUserText.string("水平翻转", "Flip Horizontal"),
                NativeScreenshotUserText.string("垂直翻转", "Flip Vertical")
            ].enumerated() {
                let item = transforms.addItem(withTitle: title,
                    action: #selector(transformFromMenu(_:)), keyEquivalent: "")
                item.tag = index
                item.target = self
            }
            let transformItem = NSMenuItem(title: NativeScreenshotUserText.string(
                "变换", "Transform"), action: nil, keyEquivalent: "")
            transformItem.submenu = transforms
            menu.addItem(transformItem)
            menu.addItem(.separator())
            menu.addItem(withTitle: NativeScreenshotUserText.string("用其他应用打开…", "Open With…"),
                         action: #selector(openWithApplication), keyEquivalent: "").target = self
            menu.addItem(withTitle: NativeScreenshotUserText.string("分享…", "Share…"),
                         action: #selector(shareImage), keyEquivalent: "").target = self
            menu.addItem(.separator())
            menu.addItem(withTitle: NativeScreenshotUserText.string("删除缩略图", "Delete"),
                         action: #selector(dismissFromMenu), keyEquivalent: "").target = self
            menu.addItem(.separator())
            menu.addItem(withTitle: NativeScreenshotUserText.string("关闭全部", "Close All"),
                         action: #selector(dismissAllFromMenu), keyEquivalent: "").target = self
            menu.addItem(withTitle: NativeScreenshotUserText.string("全部保存到文件夹…", "Save All to Folder…"),
                         action: #selector(saveAllFromMenu), keyEquivalent: "").target = self
            NSMenu.popUpContextMenu(menu, with: event, for: view)
            resumeExpiry()
        }

        private func addAction(_ title: String, index: Int, to menu: NSMenu) {
            let item = menu.addItem(withTitle: title,
                                    action: #selector(performMenuAction(_:)), keyEquivalent: "")
            item.tag = index
            item.target = self
        }

        private func scheduleExpiry() {
            guard !isClosed, !NativeScreenshotThumbnailPresenter.shared.isSavingAll else { return }
            cancelExpiry()
            let task = DispatchWorkItem { [weak self] in
                guard let self else { return }
                self.dismiss()
            }
            expiry = task
            DispatchQueue.main.asyncAfter(deadline: .now() + 8, execute: task)
        }

        private func cancelExpiry() {
            expiry?.cancel()
            expiry = nil
        }

        func perform(index: Int) {
            guard !isClosed, let pngData else { return }
            switch index {
            case 0: actions.copy(pngData)
            case 1: actions.save(pngData)
            case 2: actions.pin(pngData)
            default: actions.edit(pngData)
            }
            dismiss()
        }

        @objc private func performHoverAction(_ sender: NSButton) {
            switch sender.tag {
            case 4: dismiss()
            case 5: shareImage()
            default: perform(index: sender.tag)
            }
        }
        @objc private func performMenuAction(_ sender: NSMenuItem) { perform(index: sender.tag) }
        @objc private func saveAsFromMenu() {
            guard !isClosed, let pngData else { return }
            actions.saveAs(pngData)
            dismiss()
        }
        @objc private func dismissFromMenu() { dismiss() }
        @objc private func saveAllFromMenu() { NativeScreenshotThumbnailPresenter.shared.saveAll() }
        @objc private func dismissAllFromMenu() { NativeScreenshotThumbnailPresenter.shared.dismissAll() }

        @objc private func runRecognition() {
            guard !isClosed, let pngData else { return }
            cancelExpiry()
            Task { @MainActor [weak self] in
                do {
                    let image = try await Task.detached(priority: .userInitiated) {
                        guard let source = CGImageSourceCreateWithData(pngData as CFData, nil),
                              let image = CGImageSourceCreateImageAtIndex(source, 0, nil) else {
                            throw NativeScreenshotImageProcessor.ImageError.invalidImage
                        }
                        return image
                    }.value
                    NativeScreenshotRecognitionWindowController.open(
                        image: image,
                        language: PreferencesManager.shared.screenshotOCRLanguage,
                        initialIntent: .both,
                        onRedactedImage: { [weak self] image in
                            Task { @MainActor in
                                do {
                                    let captured = NativeScreenshotCapturedImage(
                                        image: image,
                                        sourceRect: CGRect(x: 0, y: 0,
                                            width: CGFloat(image.width),
                                            height: CGFloat(image.height)),
                                        pixelsPerPoint: 1)
                                    let delivery = try await NativeScreenshotDeliveryService.deliver(
                                        captured, action: .copy)
                                    self?.installImage(image, pngData: delivery.historyPNG)
                                } catch {
                                    NSAlert(error: error).runModal()
                                }
                            }
                        }
                    )
                } catch {
                    NSAlert(error: error).runModal()
                }
                self?.resumeExpiry()
            }
        }

        @objc private func transformFromMenu(_ sender: NSMenuItem) {
            guard !isClosed, !isProcessingImage, let pngData else { return }
            isProcessingImage = true
            cancelExpiry()
            let transform = sender.tag
            Task { @MainActor [weak self] in
                do {
                    let result = try await Task.detached(priority: .userInitiated) {
                        guard let source = CGImageSourceCreateWithData(pngData as CFData, nil),
                              let image = CGImageSourceCreateImageAtIndex(source, 0, nil) else {
                            throw NativeScreenshotImageProcessor.ImageError.invalidImage
                        }
                        let transformed: CGImage
                        switch transform {
                        case 0: transformed = try NativeScreenshotImageEditor.rotate(
                            image, clockwiseDegrees: -90)
                        case 1: transformed = try NativeScreenshotImageEditor.rotate(
                            image, clockwiseDegrees: 90)
                        case 2: transformed = try NativeScreenshotImageEditor.flip(
                            image, horizontal: true, vertical: false)
                        default: transformed = try NativeScreenshotImageEditor.flip(
                            image, horizontal: false, vertical: true)
                        }
                        let data = try NativeScreenshotImageProcessor.encode(transformed, as: .png)
                        return (transformed, data)
                    }.value
                    self?.installImage(result.0, pngData: result.1)
                } catch {
                    NSAlert(error: error).runModal()
                }
                self?.isProcessingImage = false
                self?.resumeExpiry()
            }
        }

        private func installImage(_ image: CGImage, pngData: Data) {
            guard !isClosed,
                  let newPreview = NativeScreenshotThumbnailPresenter.shared.makePreview(image)
            else { return }
            self.pngData = pngData
            retainedBytes = pngData.count
            preview = newPreview
            imageView.image = newPreview
            NativeScreenshotThumbnailPresenter.shared.trimCards()
        }

        @objc private func shareImage() {
            guard let pngData, let image = NSImage(data: pngData),
                  let view = window.contentView else { return }
            NSSharingServicePicker(items: [image]).show(relativeTo: view.bounds,
                                                        of: view, preferredEdge: .minY)
        }

        @objc private func openWithApplication() {
            guard let pngData else { return }
            cancelExpiry()
            isPresentingApplicationPicker = true
            let panel = NSOpenPanel()
            panel.allowedContentTypes = [.application]
            panel.canChooseFiles = true
            panel.canChooseDirectories = false
            panel.allowsMultipleSelection = false
            panel.message = NativeScreenshotUserText.string(
                "选择用于打开截图的应用", "Choose an application to open the screenshot")
            NSApp.activate(ignoringOtherApps: true)
            panel.begin { [weak self] response in
                guard let self else { return }
                self.isPresentingApplicationPicker = false
                guard response == .OK, let application = panel.url else {
                    self.scheduleExpiry()
                    return
                }
                Task { @MainActor [weak self] in
                    do {
                        let imageURL = try await Task.detached(priority: .userInitiated) {
                            let folder = FileManager.default.temporaryDirectory
                                .appendingPathComponent("ClipyClone-OpenWith", isDirectory: true)
                            try FileManager.default.createDirectory(
                                at: folder, withIntermediateDirectories: true)
                            let url = folder.appendingPathComponent(
                                "ClipyClone-\(UUID().uuidString).png")
                            try pngData.write(to: url, options: .atomic)
                            return url
                        }.value
                        NSWorkspace.shared.open([imageURL], withApplicationAt: application,
                                                configuration: NSWorkspace.OpenConfiguration()) {
                            _, error in
                            if let error { NSLog("Screenshot Open With failed: %@", error.localizedDescription) }
                        }
                        DispatchQueue.global(qos: .utility).asyncAfter(deadline: .now() + 3600) {
                            try? FileManager.default.removeItem(at: imageURL)
                        }
                        self?.dismiss()
                    } catch {
                        self?.scheduleExpiry()
                        if let window = self?.window {
                            NSAlert(error: error).beginSheetModal(for: window, completionHandler: nil)
                        }
                    }
                }
            }
        }

        @objc private func previewImage() {
            guard let pngData else { return }
            QuickLookPresenter.shared.open(pngData: pngData)
        }
    }
}
#endif
